name: Remote Deploy
on:
  push:
    branches: [ wins ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          timeout: 60s
          command_timeout: 20m
          script: |
            cd /srv/wins-nms
            git fetch origin wins
            git reset --hard origin/wins
            npm install --production
            npm install @tailwindcss/postcss
            rm -rf .next
            npm run build
            pm2 restart wins --update-env --cwd /srv/wins-nms
            pm2 save
